notifications:
  email: false

language: node_js
cache:
  directories:
    - "node_modules"

node_js:
  - "node"  # Run the latest version of node
  - "lts/*" # Run the latest LTS version of node

script:
- npm run bootstrap
- npm run test

after_script:
- npm run report-coverage